name: iywt
description: "Exchange Mobile Application"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.1
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_markdown: ^0.7.4+1

  # State Management & Routing
  get: ^4.7.2
  go_router: ^15.1.2
  get_it: ^8.0.3

  # Network & API
  http: ^1.4.0
  internet_connection_checker_plus: ^2.7.2
  cached_network_image: ^3.4.1

  # Device, Files & Permissions
  image_picker: ^1.1.2
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  pdf: ^3.11.3
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0

  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  local_auth: ^2.3.0

  # Utilities
  logger: ^2.5.0
  url_launcher: ^6.3.2
  flutter_verification_code: ^1.1.7
  pin_code_fields: ^8.0.1
  device_preview: ^1.2.0
  cunning_document_scanner: ^1.3.1
  cupertino_icons: ^1.0.5
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.3

flutter_gen:
  output: lib/core/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios:
    remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/